#!/usr/bin/env bash
#
# Wrapper for AWS CLI to view/edit AutoScaling Group size
#

help_function () {
  cat <<EOF
  Usage: aws-autoscaling-size [-hprniad] [--help] [--profile] [--region] [--name ASG_NAME] [--min] [--max] [--desired]

  Optional Arguments:
    -h, --help      show this help
    -p, --profile   AWS profile
    -r, --region    AWS Region (default eu-west-2)
    -n, --name      AutoScaling Group Name (leave blank to list groups)
    -i, --min       ASG new min size
    -a, --max       ASG new max size
    -d, --desired   ASG new desired size
EOF
  exit 0
}

if ! command -v aws &> /dev/null
then
    echo "\"aws-cli\" command not found!"
    exit
fi

if ! command -v jq &> /dev/null
then
    echo "\"jq\" command not found!"
    exit
fi

PROFILE=""
REGION="eu-west-2"
NAME=""
MIN=""
MAX=""
DESIRED=""

while [[ $# -gt 0 ]]
do
    case $1 in
        -h|--help)
            help_function
            ;;
        -p|--profile)
            PROFILE="$2"
            shift
            ;;
        -r|--region)
            REGION="$2"
            shift
            ;;
        -n|--name)
            NAME="$2"
            shift
            ;;
        -i|--min)
            MIN="$2"
            shift
            ;;
        -a|--max)
            MAX="$2"
            shift
            ;;
        -d|--desired)
            DESIRED="$2"
            shift
            ;;
    esac
    shift
done

echo "Profile: $PROFILE Region: $REGION"

if [ ! -z $NAME ]
then
  UPDATE="--auto-scaling-group-name $NAME"

  if [ ! -z $MIN ]
  then
    UPDATE="$UPDATE --min-size $MIN"
  fi

  if [ ! -z $MAX ]
  then
    UPDATE="$UPDATE --max-size $MAX"
  fi

  if [ ! -z $DESIRED ]
  then
    UPDATE="$UPDATE --desired-capacity $DESIRED"
  fi

  aws --profile $PROFILE --region $REGION autoscaling update-auto-scaling-group $UPDATE
  aws --profile $PROFILE --region $REGION autoscaling describe-auto-scaling-groups | jq --arg NAME $NAME '.AutoScalingGroups | .[] | select(.AutoScalingGroupName == $NAME) | "\(.MinSize) >= \(.DesiredCapacity) <= \(.MaxSize) \(.AutoScalingGroupName)"'
else
  aws --profile $PROFILE --region $REGION autoscaling describe-auto-scaling-groups | jq '.AutoScalingGroups | .[] | "\(.MinSize) >= \(.DesiredCapacity) <= \(.MaxSize) \(.AutoScalingGroupName)"'
fi
